#define DB_STATE_OPEN 1
#define DB_STATE_CLOSE 0
//TODO change db name
#define DB_NAME "data.db"

//Table user
#define DB_TABLE_USER "user"
#define DB_TABLE_USER_ID "id"
#define DB_TABLE_USER_USERNAME "username"
#define DB_TABLE_USER_PASSWORD "password"
#define DB_TABLE_USER_IMAGE "image"

//Queries
#define DB_QUERY_INIT_USER "CREATE TABLE IF NOT EXISTS " DB_TABLE_USER "(" DB_TABLE_USER_ID " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " DB_TABLE_USER_USERNAME " TEXT NOT NULL, " DB_TABLE_USER_PASSWORD " TEXT NOT NULL ," DB_TABLE_USER_IMAGE " TEXT);"

#define DB_QUERY_INIT DB_QUERY_INIT_USER
